# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMedHistories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historyType', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='UserMedHistories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allMedHistories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApi.AllMedHistories')),
                ('userProfiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApi.UserProfiles')),
            ],
        ),
    ]
