# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0002_allmedhistories_usermedhistories'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('eventType', models.IntegerField()),
                ('minAge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maxAge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timelineDescription', models.TextField()),
                ('counselingText', models.TextField(null=True)),
                ('gender', models.IntegerField(default=0)),
                ('allMedHistories1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistories1', to='mainApi.AllMedHistories')),
                ('allMedHistories2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistories2', to='mainApi.AllMedHistories')),
                ('allMedHistories3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistories3', to='mainApi.AllMedHistories')),
                ('allMedHistories4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistories4', to='mainApi.AllMedHistories')),
                ('allMedHistories5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistories5', to='mainApi.AllMedHistories')),
                ('allMedHistories6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistories6', to='mainApi.AllMedHistories')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserCreatedEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.IntegerField()),
                ('withWhom', models.CharField(max_length=100, null=True)),
                ('eventDate', models.DateField()),
                ('description', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.IntegerField(default=0, null=True)),
                ('dateCompleted', models.DateField(null=True)),
                ('shared', models.IntegerField(default=0)),
                ('allEvents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApi.AllEvents')),
            ],
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='completionPercentage',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userevents',
            name='userProfiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApi.UserProfiles'),
        ),
        migrations.AddField(
            model_name='usercreatedevents',
            name='userProfiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApi.UserProfiles'),
        ),
        migrations.AddField(
            model_name='likes',
            name='userEvents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApi.UserEvents'),
        ),
        migrations.AddField(
            model_name='likes',
            name='userProfiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApi.UserProfiles'),
        ),
        migrations.AddField(
            model_name='comments',
            name='userEvents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApi.UserEvents'),
        ),
        migrations.AddField(
            model_name='comments',
            name='userProfiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApi.UserProfiles'),
        ),
    ]
