# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0004_auto_20161031_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('eventType', models.IntegerField()),
                ('minAge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maxAge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timelineDescription', models.TextField()),
                ('counselingText', models.TextField(null=True)),
                ('gender', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AllMedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historyType', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.IntegerField(default=0, null=True)),
                ('dateCompleted', models.DateField(null=True)),
                ('shared', models.IntegerField(default=0)),
                ('allEvent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApi.AllEvent')),
            ],
        ),
        migrations.RenameModel(
            old_name='UserCreatedEvents',
            new_name='UserCreatedEvent',
        ),
        migrations.RenameModel(
            old_name='UserProfiles',
            new_name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='allevents',
            name='allMedHistories1',
        ),
        migrations.RemoveField(
            model_name='allevents',
            name='allMedHistories2',
        ),
        migrations.RemoveField(
            model_name='allevents',
            name='allMedHistories3',
        ),
        migrations.RemoveField(
            model_name='allevents',
            name='allMedHistories4',
        ),
        migrations.RemoveField(
            model_name='allevents',
            name='allMedHistories5',
        ),
        migrations.RemoveField(
            model_name='allevents',
            name='allMedHistories6',
        ),
        migrations.RemoveField(
            model_name='allevents',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='allmedhistories',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='userEvents',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='userProfiles',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='userEvents',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='userProfiles',
        ),
        migrations.RemoveField(
            model_name='userevents',
            name='allEvents',
        ),
        migrations.RemoveField(
            model_name='userevents',
            name='userProfiles',
        ),
        migrations.RenameField(
            model_name='usercreatedevent',
            old_name='userProfiles',
            new_name='userProfile',
        ),
        migrations.DeleteModel(
            name='AllEvents',
        ),
        migrations.DeleteModel(
            name='AllMedHistories',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='UserEvents',
        ),
        migrations.AddField(
            model_name='userevent',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApi.UserProfile'),
        ),
        migrations.AddField(
            model_name='like',
            name='userEvent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApi.UserEvent'),
        ),
        migrations.AddField(
            model_name='like',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApi.UserProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userEvent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApi.UserEvent'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApi.UserProfile'),
        ),
        migrations.AddField(
            model_name='allmedhistory',
            name='userMedHistory',
            field=models.ManyToManyField(related_name='UserMedHistory', to='mainApi.UserProfile'),
        ),
        migrations.AddField(
            model_name='allevent',
            name='allMedHistory1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistory1', to='mainApi.AllMedHistory'),
        ),
        migrations.AddField(
            model_name='allevent',
            name='allMedHistory2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistory2', to='mainApi.AllMedHistory'),
        ),
        migrations.AddField(
            model_name='allevent',
            name='allMedHistory3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistory3', to='mainApi.AllMedHistory'),
        ),
        migrations.AddField(
            model_name='allevent',
            name='allMedHistory4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistory4', to='mainApi.AllMedHistory'),
        ),
        migrations.AddField(
            model_name='allevent',
            name='allMedHistory5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistory5', to='mainApi.AllMedHistory'),
        ),
        migrations.AddField(
            model_name='allevent',
            name='allMedHistory6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistory6', to='mainApi.AllMedHistory'),
        ),
        migrations.AddField(
            model_name='allevent',
            name='profile',
            field=models.ManyToManyField(through='mainApi.UserEvent', to='mainApi.UserProfile'),
        ),
    ]
