# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0005_auto_20161031_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmedhistory',
            name='userMedHistory',
            field=models.ManyToManyField(null=True, related_name='UserMedHistory', to='mainApi.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userComment', to='mainApi.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('userProfile', 'userEvent')]),
        ),
    ]
