# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0006_auto_20161101_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allevent',
            name='allMedHistory1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistory1', to='mainApi.AllMedHistory'),
        ),
        migrations.AlterField(
            model_name='allevent',
            name='allMedHistory2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistory2', to='mainApi.AllMedHistory'),
        ),
        migrations.AlterField(
            model_name='allevent',
            name='allMedHistory3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistory3', to='mainApi.AllMedHistory'),
        ),
        migrations.AlterField(
            model_name='allevent',
            name='allMedHistory4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistory4', to='mainApi.AllMedHistory'),
        ),
        migrations.AlterField(
            model_name='allevent',
            name='allMedHistory5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistory5', to='mainApi.AllMedHistory'),
        ),
        migrations.AlterField(
            model_name='allevent',
            name='allMedHistory6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllEvents_allMedHistory6', to='mainApi.AllMedHistory'),
        ),
        migrations.AlterField(
            model_name='allevent',
            name='counselingText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allmedhistory',
            name='userMedHistory',
            field=models.ManyToManyField(blank=True, null=True, related_name='UserMedHistory', to='mainApi.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userEvent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApi.UserEvent'),
        ),
        migrations.AlterField(
            model_name='like',
            name='userEvent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApi.UserEvent'),
        ),
        migrations.AlterField(
            model_name='usercreatedevent',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usercreatedevent',
            name='withWhom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='allEvent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApi.AllEvent'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='completed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='dateCompleted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='completionPercentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
