# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0007_auto_20161101_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmedhistory',
            name='userMedHistory',
            field=models.ManyToManyField(blank=True, related_name='UserMedHistory', to='mainApi.UserProfile'),
        ),
    ]
