# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0008_auto_20161101_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allmedhistory',
            name='userMedHistory',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allMedHistories',
            field=models.ManyToManyField(blank=True, related_name='allMedHistories', to='mainApi.AllMedHistory'),
        ),
    ]
