# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0010_auto_20161101_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userEvent',
            new_name='userEvents',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userProfile',
            new_name='userProfiles',
        ),
        migrations.RemoveField(
            model_name='allevent',
            name='profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allEvents',
            field=models.ManyToManyField(related_name='allEvents', through='mainApi.UserEvent', to='mainApi.AllEvent'),
        ),
        migrations.AlterField(
            model_name='usercreatedevent',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCreatedEvent', to='mainApi.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('userProfiles', 'userEvents')]),
        ),
    ]
