# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0011_auto_20161101_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='dateShared',
            field=models.DateField(blank=True, null=True),
        ),
    ]
