# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0012_userevent_dateshared'),
    ]

    operations = [
        migrations.AddField(
            model_name='allevent',
            name='personalFeedDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allevent',
            name='publicFeedDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentTime',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userevent',
            name='allEvent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventsOfUser', to='mainApi.AllEvent'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whichUser', to='mainApi.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([]),
        ),
    ]
