# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0014_auto_20161106_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userevent',
            old_name='shared',
            new_name='isShared',
        ),
    ]
