# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0015_auto_20161106_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentTime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='allEvent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventOfUser', to='mainApi.AllEvent'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userOfEvent', to='mainApi.UserProfile'),
        ),
    ]
