# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0016_auto_20161107_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='isShared',
        ),
        migrations.AddField(
            model_name='userevent',
            name='ifShared',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='allEvent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otherEventInfo', to='mainApi.AllEvent'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventsOfUser', to='mainApi.UserProfile'),
        ),
    ]
