# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0018_auto_20161110_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allEvents',
            field=models.ManyToManyField(blank=True, related_name='allEvents', through='mainApi.UserEvent', to='mainApi.AllEvent'),
        ),
    ]
