# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApi', '0020_auto_20161111_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='userProfiles',
        ),
        migrations.RemoveField(
            model_name='like',
            name='userProfile',
        ),
        migrations.RemoveField(
            model_name='usercreatedevent',
            name='userProfile',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='userProfile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allEvents',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allMedHistories',
        ),
        migrations.AddField(
            model_name='allevent',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='allEvents', through='mainApi.UserEvent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allmedhistory',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='allMedHistories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercreatedevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userCreatedEvent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventsOfUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
