# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0023_auto_20161112_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allevent',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='allUserEvents', through='mainApi.UserEvent', to=settings.AUTH_USER_MODEL),
        ),
    ]
