# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0025_auto_20161114_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allmedhistory',
            options={'ordering': ['historyType']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['commentTime']},
        ),
        migrations.AlterModelOptions(
            name='userevent',
            options={'ordering': ['dateCompleted']},
        ),
        migrations.AddField(
            model_name='usercreatedevent',
            name='userEventForCreatedEvent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userEventForCreatedEvent', to='mainApi.UserEvent'),
        ),
        migrations.AlterField(
            model_name='usercreatedevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userCreatedEvents', to=settings.AUTH_USER_MODEL),
        ),
    ]
