# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0027_auto_20161125_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userevent',
            old_name='userEventForCreatedEvent',
            new_name='createdEvent',
        ),
        migrations.AlterField(
            model_name='usercreatedevent',
            name='eventDate',
            field=models.DateField(),
        ),
    ]
