# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0028_auto_20161125_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='allEvent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventInfo', to='mainApi.AllEvent'),
        ),
    ]
